### ISSUE TITLE
关于触控板手势

### ISSUE THREAD

**Issue by jxp98** [JackietYu/Hackintosh_Of_Lenovo_R720#3]
老哥，能不能说说你的触控板手势都支持哪几种额

**Comment by JackietYu** [comment]
就简单的几种，我也不这么用，你可以我试了双指，三指的上滑、左右滑动和四指与五指的的按压都是可以的

**Comment by jxp98** [comment]
> 就简单的几种，我也不这么用，你可以我试了双指，三指的上滑、左右滑动和四指与五指的的按压都是可以的

好的 谢啦

**Comment by jxp98** [comment]
> 就简单的几种，我也不这么用，你可以我试了双指，三指的上滑、左右滑动和四指与五指的的按压都是可以的

还有  老哥你hdmi解决没

**Comment by JackietYu** [comment]
> > 就简单的几种，我也不这么用，你可以我试了双指，三指的上滑、左右滑动和四指与五指的的按压都是可以的
> 
> 还有 老哥你hdmi解决没

我最近没用了，就不知道怎么样，你可以试试
