### ISSUE TITLE
更新11.2就进不去系统了

### ISSUE THREAD

**Issue by Jesselee0322** [JackietYu/Hackintosh_Of_Lenovo_R720#6]
开机屏幕左侧一条白线，然后就是无限黑屏状态，进不去系统，只能重装，哎

**Comment by JackietYu** [comment]
需要更新clover到最新版本，我这个是5128版本，已经有5130版本了

**Comment by Jesselee0322** [comment]
嗯嗯我今天更新一下试试，谢谢

**Comment by 812643806** [comment]
这个引导支持hdmi吗

**Comment by JackietYu** [comment]
> 这个引导支持hdmi吗

你好，没有测试过，1080p的屏幕真的没必要

**Comment by JackietYu** [comment]
> 嗯嗯我今天更新一下试试，谢谢

我已经更新到了11.2.3，发现更新了clover之后，没有任何问题

**Comment by Jesselee0322** [comment]
嗯嗯，我也更新clover到5131了，然后big sur升级跟白果体验一样了
